name: Build Kubernetes Connector

on:
  push:
    tags:
      - 'v*.*.*'  # Запускается только при создании тега версии (v0.0.3, v0.0.4 и т.д.)
  pull_request:
    paths:
      - 'cmd/kubernetes/**'
      - 'internal/k8s/**'
      - 'Dockerfile.k8s'
      - 'charts/catops/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/kubernetes-connector

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.k8s
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.12.0'

      - name: Lint Helm chart
        run: |
          helm lint charts/catops

      - name: Template Helm chart
        run: |
          helm template test charts/catops \
            --set auth.token=test-token \
            > /dev/null

  helm-publish:
    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')) && github.event_name == 'push'
    needs: [build, helm-lint]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.12.0'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and Publish Helm chart
        run: |
          # Package chart
          helm package charts/catops

          # Получаем версию из Chart.yaml
          CHART_VERSION=$(grep '^version:' charts/catops/Chart.yaml | awk '{print $2}')
          echo "📦 Publishing Helm chart version: $CHART_VERSION"

          # Публикуем chart в GHCR как OCI artifact
          helm push catops-${CHART_VERSION}.tgz oci://ghcr.io/${{ github.repository }}/helm-charts

          echo "✅ Helm chart published to: oci://ghcr.io/${{ github.repository }}/helm-charts/catops"

  helm-package:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs: [build, helm-lint]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.12.0'

      - name: Package Helm chart
        run: |
          helm package charts/catops

      - name: Upload Helm chart artifact
        uses: actions/upload-artifact@v3
        with:
          name: helm-chart
          path: catops-*.tgz

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Helm chart to GHCR
        run: |
          # Получаем версию из Chart.yaml
          CHART_VERSION=$(grep '^version:' charts/catops/Chart.yaml | awk '{print $2}')
          echo "📦 Publishing Helm chart version: $CHART_VERSION"

          # Публикуем chart в GHCR как OCI artifact
          helm push catops-${CHART_VERSION}.tgz oci://ghcr.io/${{ github.repository }}/helm-charts

          echo "✅ Helm chart published to: oci://ghcr.io/${{ github.repository }}/helm-charts/catops:$CHART_VERSION"
